# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plink',
            fields=[
                ('plink_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=b'', max_length=256)),
                ('prefab_path', models.CharField(blank=True, default=b'', max_length=256)),
                ('options_str', models.CharField(blank=True, default=b'{}', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PlinkJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=128, null=True)),
                ('status', models.CharField(choices=[(b'0', b'Job Not Ready'), (b'101', b'Job Pending'), (b'111', b'Job Ready'), (b'121', b'Job Scheduled'), (b'131', b'Job Processing'), (b'141', b'Job Error'), (b'888', b'Cancelled'), (b'999', b'All Completed')], default=b'0', max_length=64)),
                ('plink_id', models.CharField(blank=True, default=b'', max_length=64)),
                ('result_text', models.CharField(blank=True, default=b'', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='PlinkOption',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('plink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plink.Plink')),
            ],
        ),
        migrations.CreateModel(
            name='PlinkPrefabs',
            fields=[
                ('config_id', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('selected_prefab_id', models.CharField(max_length=64)),
                ('selected_prefab_path', models.CharField(max_length=264)),
            ],
        ),
    ]
