# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plinkoption',
            name='id',
            field=models.AutoField(auto_created=True, default=4251129, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plinkoption',
            name='key',
            field=models.CharField(max_length=64),
        ),
    ]
