# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plink', '0002_auto_20160426_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='plinkoption',
            name='type',
            field=models.CharField(choices=[(b'OPT_TEXT', b'Text String Option'), (b'OPT_FILE', b'File Path Option'), (b'OPT_DIR', b'Directory Path Option'), (b'OPT_BOOL', b'Boolean Flag Option'), (b'OPT_INT', b'Integer Value Option'), (b'OPT_FLOAT', b'Floating Point Value Option')], default=b'OPT_TEXT', max_length=64),
        ),
    ]
