# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plink', '0003_plinkoption_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plink',
            name='pretty_name',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
    ]
